pipeline {
    agent any

    environment {
        MAVEN_HOME = '/opt/maven'
        PATH = "/opt/maven/bin:$PATH"
    }

    stages {
        stage('Build') {
            steps {
                sh '${MAVEN_HOME}/bin/mvn -B -DskipTests clean package'
            }
        }

        stage('Test') {
            steps {
                sh '${MAVEN_HOME}/bin/mvn test'
                junit '**/target/surefire-reports/*.xml'
            }
        }

        stage('Deliver') {
            steps {
                sh 'chmod +x ./jenkins/scripts/deliver.sh'
                sh 'export PATH=/opt/maven/bin:$PATH && ./jenkins/scripts/deliver.sh'
            }
        }
    }
}
