pipeline {
    agent any
    tools {
        jdk 'Java21'
        maven 'Maven3.9.11'
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn clean install'
            }
        }
    }
}
