pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            steps {
                sh '/opt/maven/bin/mvn mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh '/opt/maven/bin/mvn mvn test'
            }
            post {
                always {
                    junit '/opt/maven/bin/mvn target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') { 
            steps {
                sh './jenkins/scripts/deliver.sh' 
            }
        }
    }
}
